name: push container

on:
  push:
    branches:
    - master
  schedule:
    - cron: "30 0 * * 2/5"

jobs:
  main:
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: ubuntu-20.04
    steps:
      -
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bbsdocker/imageptt:latest,bbsdocker/imageptt:${{ steps.date.outputs.date }}
          build-args: |
            MY_DEBIAN_VERSION=bullseye

      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
