name: push container

on:
  push:
    branches: master
  schedule:
    - cron: "30 16 * * 0,4"

jobs:
  main:
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: ubuntu-22.04
    steps:
      -
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: bbsdocker/imageptt:sid,bbsdocker/imageptt:sid-latest,bbsdocker/imageptt:sid-${{ steps.date.outputs.date }}
          build-args: |
            MY_DEBIAN_VERSION=sid

      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      -
        name: Build and push - arm64
        id: docker_build_arm64
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: bbsdocker/imageptt:sid,bbsdocker/imageptt:sid-latest,bbsdocker/imageptt:sid-${{ steps.date.outputs.date }}
          platforms: linux/arm64
          build-args:
            - MY_DEBIAN_VERSION=sid
            - OPENRESTY_ARCH=arm64
      -
        name: Image digest - arm64
        run: echo ${{ steps.docker_build_arm64.outputs.digest }}
